const RETRIEVE_EVENTS_REQUEST = "RETRIEVE_EVENTS_REQUEST";
const RETRIEVE_EVENTS_SUCCESS = "RETRIEVE_EVENTS_SUCCESS";
const RETRIEVE_EVENTS_ERROR = "RETRIEVE_EVENTS_ERROR";

const RETRIEVE_BOOKINGS_REQUEST = "RETRIEVE_BOOKINGS_REQUEST";
const RETRIEVE_BOOKINGS_SUCCESS = "RETRIEVE_BOOKINGS_SUCCESS";
const RETRIEVE_BOOKINGS_ERROR = "RETRIEVE_BOOKINGS_ERROR";

const LOAD_FEED_REQUEST = "LOAD_FEED_REQUEST";
const LOAD_FEED_SUCCESS = "LOAD_FEED_SUCCESS";
const LOAD_FEED_ERROR = "LOAD_FEED_ERROR";

const BOOK_EVENT_REQUEST = "BOOK_EVENT_REQUEST";
const BOOK_EVENT_SUCCESS = "BOOK_EVENT_SUCCESS";
const BOOK_EVENT_ERROR = "BOOK_EVENT_ERROR";

export default {
    RETRIEVE_EVENTS_REQUEST,
    RETRIEVE_EVENTS_SUCCESS,
    RETRIEVE_EVENTS_ERROR,
    RETRIEVE_BOOKINGS_REQUEST,
    RETRIEVE_BOOKINGS_SUCCESS,
    RETRIEVE_BOOKINGS_ERROR,
    LOAD_FEED_REQUEST,
    LOAD_FEED_SUCCESS,
    LOAD_FEED_ERROR,
    BOOK_EVENT_REQUEST,
    BOOK_EVENT_SUCCESS,
    BOOK_EVENT_ERROR
};
