const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";

const UPDATE_BOOKING_STATUS_REQUEST = "UPDATE_BOOKING_STATUS_REQUEST";
const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
const UPDATE_BOOKING_STATUS_ERROR = "UPDATE_BOOKING_STATUS_ERROR";

const GET_BOOKINGS_BY_EVENT_SUCCESS = "GET_BOOKINGS_BY_EVENT_SUCCESS";
const GET_BOOKINGS_ERROR = "GET_BOOKINGS_ERROR";
export default {
    CREATE_BOOKING_REQUEST,
    CREATE_BOOKING_SUCCESS,
    CREATE_BOOKING_ERROR,
    UPDATE_BOOKING_STATUS_REQUEST,
    UPDATE_BOOKING_STATUS_SUCCESS,
    UPDATE_BOOKING_STATUS_ERROR,
    GET_BOOKINGS_BY_EVENT_SUCCESS,
    GET_BOOKINGS_ERROR
};
