const GET_CURRENT_BOOKINGS_REQUEST = "GET_CURRENT_BOOKINGS_REQUEST";
const GET_CURRENT_BOOKINGS_SUCCESS = "GET_CURRENT_BOOKINGS_SUCCESS";
const GET_CURRENT_BOOKINGS_ERROR = "GET_CURRENT_BOOKINGS_ERROR";

const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";

export default {
    GET_CURRENT_BOOKINGS_SUCCESS,
    GET_CURRENT_BOOKINGS_REQUEST,
    GET_CURRENT_BOOKINGS_ERROR,
    CREATE_BOOKING_REQUEST,
    CREATE_BOOKING_SUCCESS,
    CREATE_BOOKING_ERROR
};
