const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";

export default {
    GET_NOTIFICATIONS_ERROR,
    GET_NOTIFICATIONS_REQUEST,
    GET_NOTIFICATIONS_SUCCESS
};
