const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

const UPLOAD_USER_IMAGE_REQUEST = "UPLOAD_USER_IMAGE_REQUEST";
const UPLOAD_USER_IMAGE_SUCCESS = "UPLOAD_USER_IMAGE_SUCCESS";
const UPLOAD_USER_IMAGE_ERROR = "UPLOAD_USER_IMAGE_ERROR";

const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST";
const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
const GET_BOOKINGS_ERROR = "GET_BOOKINGS_ERROR";

const SAVE_PAYMENT_REQUEST = "SAVE_PAYMENT_REQUEST";
const SAVE_PAYMENT_SUCCESS = "SAVE_PAYMENT_SUCCESS";
const SAVE_PAYMENT_ERROR = "SAVE_PAYMENT_ERROR";

const GET_AVATAR_REQUEST = "GET_AVATAR_REQUEST";
const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS";
const GET_AVATAR_ERROR = "GET_AVATAR_ERROR";

const GET_CURRENT_BOOKINGS_REQUEST = "GET_CURRENT_BOOKINGS_REQUEST";
const GET_CURRENT_BOOKINGS_SUCCESS = "GET_CURRENT_BOOKINGS_SUCCESS";
const GET_CURRENT_BOOKINGS_ERROR = "GET_CURRENT_BOOKINGS_ERROR";

export default {
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCCESS,
    UPDATE_USER_ERROR,
    UPLOAD_USER_IMAGE_REQUEST,
    UPLOAD_USER_IMAGE_SUCCESS,
    UPLOAD_USER_IMAGE_ERROR,
    GET_BOOKINGS_REQUEST,
    GET_BOOKINGS_SUCCESS,
    GET_BOOKINGS_ERROR,
    SAVE_PAYMENT_REQUEST,
    SAVE_PAYMENT_SUCCESS,
    SAVE_PAYMENT_ERROR,
    GET_AVATAR_REQUEST,
    GET_AVATAR_SUCCESS,
    GET_AVATAR_ERROR,
    GET_CURRENT_BOOKINGS_ERROR,
    GET_CURRENT_BOOKINGS_REQUEST,
    GET_CURRENT_BOOKINGS_SUCCESS
};
