const GET_CHEF_REQUEST = "GET_CHEF_REQUEST";
const GET_CHEF_SUCCESS = "GET_CHEF_SUCCESS";
const GET_CHEF_ERROR = "GET_CHEF_ERROR";

const CREATE_APPLICATION_REQUEST = "CREATE_APPLICATION_REQUEST";
const CREATE_APPLICATION_SUCCESS = "CREATE_APPLICATION_SUCCESS";
const CREATE_APPLICATION_ERROR = "CREATE_APPLICATION_ERROR";

export default {
    GET_CHEF_ERROR,
    GET_CHEF_SUCCESS,
    GET_CHEF_REQUEST,
    CREATE_APPLICATION_REQUEST,
    CREATE_APPLICATION_SUCCESS,
    CREATE_APPLICATION_ERROR
};
