const GET_CHEF_REQUEST = "GET_CHEF_REQUEST";
const GET_CHEF_SUCCESS = "GET_CHEF_SUCCESS";
const GET_CHEF_ERROR = "GET_CHEF_ERROR";

const CREATE_APPLICATION_REQUEST = "CREATE_APPLICATION_REQUEST";
const CREATE_APPLICATION_SUCCESS = "CREATE_APPLICATION_SUCCESS";
const CREATE_APPLICATION_ERROR = "CREATE_APPLICATION_ERROR";

const LOAD_HOSTING_EVENTS_REQUEST = "LOAD_HOSTING_EVENTS_REQUEST";
const LOAD_HOSTING_EVENTS_SUCCESS = "LOAD_HOSTING_EVENTS_SUCCESS";
const LOAD_HOSTING_EVENTS_ERROR = "LOAD_HOSTING_EVENTS_ERROR";

const POST_EVENT_REQUEST = "POST_EVENT_REQUEST";
const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
const POST_EVENT_ERROR = "POST_EVENT_ERROR";

const UPDATE_ACCOUNT_ID = "UPDATE_ACCOUNT_ID";

const UPDATE_HOST_REQUEST = "UPDATE_HOST_REQUEST";
const UPDATE_HOST_SUCCESS = "UPDATE_HOST_SUCCESS";
const UPDATE_HOST_ERROR = "UPDATE_HOST_ERROR";

const UPLOAD_HOST_IMAGE_REQUEST = "UPLOAD_HOST_IMAGE_REQUEST";
const UPLOAD_HOST_IMAGE_SUCCESS = "UPLOAD_HOST_IMAGE_SUCCESS";
const UPLOAD_HOST_IMAGE_ERROR = "UPLOAD_HOST_IMAGE_ERROR";

const GET_HOST_AVATAR_REQUEST = "GET_HOST_AVATAR_REQUEST";
const GET_HOST_AVATAR_SUCCESS = "GET_HOST_AVATAR_SUCCESS";
const GET_HOST_AVATAR_ERROR = "GET_HOST_AVATAR_ERROR";

export default {
    GET_CHEF_ERROR,
    GET_CHEF_SUCCESS,
    GET_CHEF_REQUEST,
    CREATE_APPLICATION_REQUEST,
    CREATE_APPLICATION_SUCCESS,
    CREATE_APPLICATION_ERROR,
    LOAD_HOSTING_EVENTS_REQUEST,
    LOAD_HOSTING_EVENTS_SUCCESS,
    LOAD_HOSTING_EVENTS_ERROR,
    POST_EVENT_REQUEST,
    POST_EVENT_SUCCESS,
    POST_EVENT_ERROR,
    UPDATE_ACCOUNT_ID,
    UPDATE_HOST_REQUEST,
    UPDATE_HOST_SUCCESS,
    UPDATE_HOST_ERROR,
    UPLOAD_HOST_IMAGE_REQUEST,
    UPLOAD_HOST_IMAGE_SUCCESS,
    UPLOAD_HOST_IMAGE_ERROR,
    GET_HOST_AVATAR_REQUEST,
    GET_HOST_AVATAR_SUCCESS,
    GET_HOST_AVATAR_ERROR
};
