const GET_CHEF_REQUEST = "GET_CHEF_REQUEST";
const GET_CHEF_SUCCESS = "GET_CHEF_SUCCESS";
const GET_CHEF_ERROR = "GET_CHEF_ERROR";

const CREATE_APPLICATION_REQUEST = "CREATE_APPLICATION_REQUEST";
const CREATE_APPLICATION_SUCCESS = "CREATE_APPLICATION_SUCCESS";
const CREATE_APPLICATION_ERROR = "CREATE_APPLICATION_ERROR";

const LOAD_HOSTING_EVENTS_REQUEST = "LOAD_HOSTING_EVENTS_REQUEST";
const LOAD_HOSTING_EVENTS_SUCCESS = "LOAD_HOSTING_EVENTS_SUCCESS";
const LOAD_HOSTING_EVENTS_ERROR = "LOAD_HOSTING_EVENTS_ERROR";

const CANCEL_EVENT_REQUEST = "CANCEL_EVENT_REQUEST";
const CANCEL_EVENT_SUCCESS = "CANCEL_EVENT_SUCCESS";
const CANCEL_EVENT_ERROR = "CANCEL_EVENT_ERROR";

const POST_EVENT_REQUEST = "POST_EVENT_REQUEST";
const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
const POST_EVENT_ERROR = "POST_EVENT_ERROR";

const UPDATE_ACCOUNT_ID = "UPDATE_ACCOUNT_ID";

export default {
    GET_CHEF_ERROR,
    GET_CHEF_SUCCESS,
    GET_CHEF_REQUEST,
    CREATE_APPLICATION_REQUEST,
    CREATE_APPLICATION_SUCCESS,
    CREATE_APPLICATION_ERROR,
    LOAD_HOSTING_EVENTS_REQUEST,
    LOAD_HOSTING_EVENTS_SUCCESS,
    LOAD_HOSTING_EVENTS_ERROR,
    CANCEL_EVENT_REQUEST,
    CANCEL_EVENT_SUCCESS,
    CANCEL_EVENT_ERROR,
    POST_EVENT_REQUEST,
    POST_EVENT_SUCCESS,
    POST_EVENT_ERROR,
    UPDATE_ACCOUNT_ID
};
