const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";

const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_ERROR = "SIGNUP_ERROR";

const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";

const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";
const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
const SIGNOUT_ERROR = "SIGNOUT_ERROR";

const AUTO_LOGIN_START = "AUTO_LOGIN_START";
const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
const AUTO_LOGIN_ERROR = "AUTO_LOGIN_SUCCESS";

const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST";

export default {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    SIGNUP_REQUEST,
    SIGNUP_SUCCESS,
    SIGNUP_ERROR,
    PASSWORD_RESET_ERROR,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,
    SIGNOUT_ERROR,
    SIGNOUT_REQUEST,
    SIGNOUT_SUCCESS,
    AUTO_LOGIN_START,
    AUTO_LOGIN_SUCCESS,
    AUTO_LOGIN_ERROR,
    REFRESH_TOKEN_REQUEST
};
