# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homecooked' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Homecooked
  pod 'UrbanAirship-iOS-SDK', '~>10.0'
  
  # pod 'react-native-branch', :path => '../node_modules/react-native-branch'
  # pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'
  
  target 'HomecookedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

