# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homecooked' do
  pod 'Stripe', '~> 14.0.0'
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Homecooked
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'UrbanAirship-iOS-SDK', '~>11.0'
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'FBSDKCoreKit', '~>4.42.0'
  pod 'FBSDKLoginKit', '~>4.42.0'
  pod 'FBSDKShareKit', '~>4.42.0'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNColorMatrixImageFilters', :path => '../node_modules/react-native-color-matrix-image-filters'

  platform :ios, '9.0'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    if target.name == "React"
      target.remove_from_project
    end
  end
end

