const GET_EVENTS_REQUEST = "GET_ACTIVE_EVENTS_REQUEST";
const GET_EVENTS_SUCCESS = "GET_ACTIVE_EVENTS_SUCCESS";
const GET_EVENTS_ERROR = "GET_ACTIVE_EVENTS_ERROR";

const GET_RELATED_EVENT_REQUEST = "GET_RELATED_EVENT_REQUEST";
const GET_RELATED_EVENT_SUCCESS = "GET_RELATED_EVENT_SUCCESS";
const GET_RELATED_EVENT_ERROR = "GET_RELATED_EVENT_ERROR";

const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
const GET_EVENT_ERROR = "GET_EVENT_ERROR";

const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
const UPDATE_EVENT_ERROR = "UPDATE_EVENT_ERROR";

export default {
    GET_EVENTS_REQUEST,
    GET_EVENTS_SUCCESS,
    GET_EVENTS_ERROR,
    GET_RELATED_EVENT_ERROR,
    GET_RELATED_EVENT_REQUEST,
    GET_RELATED_EVENT_SUCCESS,
    GET_EVENT_REQUEST,
    GET_EVENT_SUCCESS,
    GET_EVENT_ERROR,
    UPDATE_EVENT_REQUEST,
    UPDATE_EVENT_SUCCESS,
    UPDATE_EVENT_ERROR
};
