const GET_EVENTS_REQUEST = "GET_ACTIVE_EVENTS_REQUEST";
const GET_EVENTS_SUCCESS = "GET_ACTIVE_EVENTS_SUCCESS";
const GET_EVENTS_ERROR = "GET_ACTIVE_EVENTS_ERROR";

const GET_RELATED_EVENT_REQUEST = "GET_RELATED_EVENT_REQUEST";
const GET_RELATED_EVENT_SUCCESS = "GET_RELATED_EVENT_SUCCESS";
const GET_RELATED_EVENT_ERROR = "GET_RELATED_EVENT_ERROR";

const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
const GET_EVENT_ERROR = "GET_EVENT_ERROR";

const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
const UPDATE_EVENT_ERROR = "UPDATE_EVENT_ERROR";

const SELECT_EVENT = "SELECT_EVENT";

const GET_EVENT_DETAILS_REQUEST = "GET_EVENT_DETAILS_REQUEST";
const GET_EVENT_DETAILS_SUCCESS = "GET_EVENT_DETAILS_SUCCESS";
const GET_EVENT_DETAILS_ERROR = "GET_EVENT_DETAILS_ERROR";

const BOOK_EVENT_REQUEST = "BOOK_EVENT_REQUEST";
const BOOK_EVENT_SUCCESS = "BOOK_EVENT_SUCCESS";
const BOOK_EVENT_ERROR = "BOOK_EVENT_ERROR";

const REFUND_BOOKING_REQUEST = "REFUND_BOOKING_REQUEST";
const REFUND_BOOKING_SUCCESS = "REFUND_BOOKING_SUCCESS";
const REFUND_BOOKING_ERROR = "REFUND_BOOKING_ERROR";

const CANCEL_EVENT_REQUEST = "CANCEL_EVENT_REQUEST";
const CANCEL_EVENT_SUCCESS = "CANCEL_EVENT_SUCCESS";
const CANCEL_EVENT_ERROR = "CANCEL_EVENT_ERROR";

const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR";

const MARK_ATTENDANCE_REQUEST = "MARK_ATTENDANCE_REQUEST";
const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
const MARK_ATTENDANCE_ERROR = "MARK_ATTENDANCE_ERROR";

const LEAVE_REVIEW_REQUEST = "LEAVE_REVIEW_REQUEST";
const LEAVE_REVIEW_SUCCESS = "LEAVE_REVIEW_SUCCESS";
const LEAVE_REVIEW_ERROR = "LEAVE_REVIEW_ERROR";

export default {
    GET_EVENTS_REQUEST,
    GET_EVENTS_SUCCESS,
    GET_EVENTS_ERROR,
    GET_RELATED_EVENT_ERROR,
    GET_RELATED_EVENT_REQUEST,
    GET_RELATED_EVENT_SUCCESS,
    GET_EVENT_REQUEST,
    GET_EVENT_SUCCESS,
    GET_EVENT_ERROR,
    UPDATE_EVENT_REQUEST,
    UPDATE_EVENT_SUCCESS,
    UPDATE_EVENT_ERROR,
    SELECT_EVENT,
    GET_EVENT_DETAILS_REQUEST,
    GET_EVENT_DETAILS_SUCCESS,
    GET_EVENT_DETAILS_ERROR,
    BOOK_EVENT_REQUEST,
    BOOK_EVENT_SUCCESS,
    BOOK_EVENT_ERROR,
    REFUND_BOOKING_REQUEST,
    REFUND_BOOKING_SUCCESS,
    REFUND_BOOKING_ERROR,
    CANCEL_EVENT_REQUEST,
    CANCEL_EVENT_SUCCESS,
    CANCEL_EVENT_ERROR,
    CREATE_EVENT_REQUEST,
    CREATE_EVENT_SUCCESS,
    CREATE_EVENT_ERROR,
    MARK_ATTENDANCE_REQUEST,
    MARK_ATTENDANCE_SUCCESS,
    MARK_ATTENDANCE_ERROR,
    LEAVE_REVIEW_REQUEST,
    LEAVE_REVIEW_SUCCESS,
    LEAVE_REVIEW_ERROR
};
