const GET_ACTIVE_EVENTS_REQUEST = "GET_ACTIVE_EVENTS_REQUEST";
const GET_ACTIVE_EVENTS_SUCCESS = "GET_ACTIVE_EVENTS_SUCCESS";
const GET_ACTIVE_EVENTS_ERROR = "GET_ACTIVE_EVENTS_ERROR";

const GET_RELATED_EVENT_REQUEST = "GET_RELATED_EVENT_REQUEST";
const GET_RELATED_EVENT_SUCCESS = "GET_RELATED_EVENT_SUCCESS";
const GET_RELATED_EVENT_ERROR = "GET_RELATED_EVENT_ERROR";

export default {
    GET_ACTIVE_EVENTS_REQUEST,
    GET_ACTIVE_EVENTS_SUCCESS,
    GET_ACTIVE_EVENTS_ERROR,
    GET_RELATED_EVENT_ERROR,
    GET_RELATED_EVENT_REQUEST,
    GET_RELATED_EVENT_SUCCESS
};
