const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

const UPLOAD_USER_IMAGE_REQUEST = "UPLOAD_USER_IMAGE_REQUEST";
const UPLOAD_USER_IMAGE_SUCCESS = "UPLOAD_USER_IMAGE_SUCCESS";
const UPLOAD_USER_IMAGE_ERROR = "UPLOAD_USER_IMAGE_ERROR";

export default {
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCCESS,
    UPDATE_USER_ERROR,
    UPLOAD_USER_IMAGE_REQUEST,
    UPLOAD_USER_IMAGE_SUCCESS,
    UPLOAD_USER_IMAGE_ERROR
};
