const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_ERROR = "GET_USER_ERROR";

export default {
    GET_USER_REQUEST,
    GET_USER_SUCCESS,
    GET_USER_ERROR
};
